version: '3.8'
services:
  drink-smart-backend:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - '8070:8080'
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: drink_smart
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
